sudo: false
language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: GHCVER=8.0.2 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.0.2

before_install:
- mkdir -p ~/.local/bin
- export PATH=/opt/ghc/$GHCVER/bin:$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test
